# Generated by Django 2.2 on 2020-02-18 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cars', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='imgUrl',
            field=models.URLField(default=''),
            preserve_default=False,
        ),
    ]
